code: 131199
gijiroku: data/gijiroku.csv
giin: data/giin.csv
iinkai: data/iinkai.csv
years: data/years.csv
jogai: data/exclusion.csv
font: static/ShipporiMinchoB1-ExtraBold.ttf
target:
  place: 大田区
  start: 1999年5月
  end: 2022年10月
  url: https://www.city.ota.tokyo.jp/gikai/kugikai_katsudou/kaigiroku.html
developer:
  name: 岡村健一
  contact: https://twitter.com/Okamura_Kenichi
  img: static/developer.png